version: 0.2
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
      - unzip terraform_0.12.18_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version 
      - TF_LOG=TRACE
      - terraform init
      - terraform plan
      - terraform apply
  build:
    commands:
      - echo "push code"
artifacts:
  files:
    - '**/*'